#!/usr/bin/python3

from tkinter import *

root = Tk()

width= root.winfo_screenwidth() 
height= root.winfo_screenheight()

root.geometry("%dx%d" % (width, height))

root.title("Infinit grid")
C = Canvas(root, bg="black")
C.grid(row=0, column=2)



C.pack()
mainloop()
